import random
import time

def Intro(name=None):
    print("Reminder: Turn on cap lock to ensure a better gaming experience!")
    time.sleep(2)
    if name == None:
        name = input("Enter your name Luminary:")
    print("In the land of Yggradsil evil has ran wild.")
    time.sleep(1)
    print("Narrator: Monsters claim the lives of the innocent")
    print("Narrator: They are becoming more powerful by each passing day.")
    time.sleep(1)
    print("Narrator: Only the Luminary is strong enough to take down whose responsible.")
    time.sleep(1)
    print("The Darkspawn.... It is his destiny to bring back the world to light.")
    time.sleep(2)
    print("Hello", name)
    time.sleep(1)
    print("Are you prepared to stop chaos and defeat the Darkspawn?")
    decision = input("Enter Y/N:", )
    time.sleep(2)
    if decision == ("Y"):
        time.sleep(1)
        print("May your quest begin")
        MainStory1(name)
        time.sleep(1)
    elif decision == "N":
        time.sleep(2)
        print ("Come back when you're ready Hero...")
        time.sleep(2)
        Restart()
    else:
        print("Invalid Answer")
        Restart()
    
def Credits():
    print("My inspiration for this text base game was the game Dragon Quest 11s")
    print("The game creator being Yuji Horii")
    print("Thanks for playing")

def Restart():
    name = input("Enter your name Luminary:")
    Intro(name)
    
def Fight():
    print("Narrator: The hero dodges it and jumps on the Darkspawn back")
    time.sleep(2)
    print("Darkspawn: You insect! Get off me!")
    time.sleep(2)
    print("Narrator: The Darkspawn takes to the sky.")
    time.sleep(2)
    print("Narrator: The Luminary strikes his sword into the Darkspawn.")
    time.sleep(2)
    print("Narrator: However, the hero needs to recite the spell to kill the dragon.")
    time.sleep(2)
    latin = input("What were they exactly? ")
    if latin == "Ut oppressa vestigia nostra fulgur revelare verum heros":
        print("Darkspawn: Impossible!!!")
        time.sleep(2)
        print("Narrator: Hundreds of previous heroes lends the hero their strength")
        time.sleep(2)
        print("Narrator: Thousands of lightning bolts strike the Darkspawn")
        time.sleep(2)
        print("Narrator: The Darkspawn is overwhelmed and defeated")
        time.sleep(2)
        print("Narrator: YOU DID IT!")
        time.sleep(2)
        print("Narrator: You won")
        time.sleep(2)
        Credits()
    else:
        print("Darkspawn: You're dead!")
        print("Narrator: The young hero falls and dies on impact.")
        RETRY = input("Try Again? Y/N")
        if RETRY == "Y":
            Restart()
        elif RETRY == "N":
            print("Narrator: Way to let us down")
        else:
            print("Invalid Answer")
            Restart()
            
def Destiny():
    print("Narrator: The hero enters his conscience where weapons appear")
    weapon = input("Select your weapon: Axe, Sword, Bow, or Nothing: ")
    if weapon == "Axe":
        Destiny()
    elif weapon == "Sword":
        Destiny()
    elif weapon == "Bow":
        Destiny()
    elif weapon == "Nothing":
        print("Why?")
        time.sleep(2)
        print("Tony: Because the power is inside me...")
        time.sleep(2)
        print("Narrator: Suddenly the lightning changes")
        time.sleep(2)
        print("Narrator: It creates a sword of lightning that only the Luminary can use.")
        time.sleep(2)
        print("Narrator: Within it is all the past Luminary's skills")
        time.sleep(2)
        print("Narrator: Not long after the clouds grew darker and a dragon appears")
        time.sleep(2)
        print("Narrator: It's scales black as night and its eyes red")
        time.sleep(2)
        print("Narrator: It was the Darkspawn")
        time.sleep(2)
        print("Narrator: The battle is here")
        time.sleep(2)
        print("Narrator: The Darkspawn swings its tail at the hero")
        time.sleep(2)
        Fight() 
        
def MeetingErik(name):
    print ("Stranger: Hey there mate! What are you doing here in a place like?")
    time.sleep(1)
    print ("Narrator: You tell them who you are and what your quest is.")
    time.sleep(1)
    print ("Stranger: HAHAHA! Seriously!")
    seriously = input("Quick what's 9 + 10?")
    if seriously == "19":
        print ("Stranger: Well, I guess you aren't a complete idiot")
        print("Erik: Well, my name's Erik and my quest was to find the Luminary.")
        time.sleep(2) 
        print("Erik: To be honest, thought he'd look older and you know not pathetic.")
        time.sleep(2)
        print("Erik: Well begger can't be chooser is what they say")
        ErikChose = input("Well, mind if I tag along? Y/N?")
        if ErikChose == ("Y"):
            print("Narrator: Erik has joined the party")
            CityTrip(name)
        elif ErikChose == ("N"):
            print("Erik: Well, looks like you're  a goner")
            print("Narrator: Erik got a cheap shot with his dagger")
            print("Narrator: You bleed out within an hour")
            RETRY = input("Try Again? Y/N")
            if RETRY == "Y":
                Restart()
            elif RETRY == "N":
                print("Narrator: Way to let us down", name)
            else:
                print("Invalid Answer")
                Restart()   
    elif seriously == ("21") or ("69") or ("420"):
        print ("......")
        time.sleep(1)
        print ("You died! Don't ask how though!")
        Restart() 
    elif ErikChose == ("N"):
        print("Erik: Well, looks like you're  a goner")
        print("Narrator: Erik got a cheap shot with his dagger")
        print("Narrator: You bleed out within an hour")
        RETRY = input("Try Again? Y/N")
        if RETRY == "Y":
            Restart()
        elif RETRY == "N":
             print("Narrator: Way to let us down", name)
        else:
            print("Invalid Answer")
            Restart()   
def MainStory1(name):
    print ("As you start your journey, you the road splits into two.")
    time.sleep(2)
    choose = input("Do you want to take the left or right past. Enter L/R:")
    time.sleep(1)
    if choose == "L":
        print("As you walk down the path you see a group of goblins.")
        time.sleep(1)
        print("Narrator: They come kill you with sticks and stones but their words never hurt you.")
        time.sleep(1)
        print("Narrator: Mostly because you didn't understand them.")
        RETRY = input("Try Again? Y/N")
        if RETRY == "Y":
            Restart()
        elif RETRY == "N":
            print("Narrator: Way to let us down", name)
        else:
            RETRY = input("Try Again? Y/N")
            print(Restart())
    elif choose == "R":
        print("Narrator: The path looks safe and you run into a young man around your age.")
        MeetingErik(name)
    else:
        print ("Error")
        time.sleep(2)
        MainStory1(name)
        
def Judgement():
    print("Jessie: The time has come for the hero to start his trial")
    time.sleep(1)
    print("Narrator: It starts by him harnessing the his luminary powers...")
    time.sleep(1)
    test = input("Jessie: This trial will give you true powers. Ready?: Y/N")
    if test == "Y":
        print("All of a sudden the city of Hoenn was covered by dark clouds...")
        time.sleep(1)
        print("The lightning symbol on your left hand starts to glow brightly")
        time.sleep(1)
        print("You raise it high into the air.")
        Destiny()
    elif test == "N":
        print("You fool judgement will show you no mercy")
        time.sleep(1)
        print("Lightning strikes you down and you scream in pain")
        time.sleep(1)
        print("You were scared to face your destiny")
        time.sleep(1)
        print("This battle won't be easy so fear is nature")
        time.sleep(1)
        print("While you are the luminary you are still human")
        time.sleep(1)
        print("Heroes aren't those who are fearless")
        time.sleep(1)
        print("Heroes are those that take fear head on and prosper")
        Destiny()
    else:
        Judgement()

def CityTrip(name):
    print("Narrator: As you travel you travel. You find and open a chest.")
    time.sleep(1)
    for gold in range (10,100,10):
        print("You found " + str(gold) + " pieces of gold.")
        time.sleep(1)
    print("Erik: Looks like it's our lucky day!")
    time.sleep(2)
    print("Narrator: Our two traveller make it to the city of Hoenn.")
    time.sleep(2)
    print("Narrator: As they get to the gate they are stopped by some guards.")
    time.sleep(2)
    print("Guard #1: What are you two doing here?")
    time.sleep(2)
    print("Narrator: The young heroes explain what their quest.")
    time.sleep(2)
    print("Guard #1 & Guard #2: Seriously!")
    time.sleep(2)
    print("Narrator: Erik looks at", name)
    time.sleep(2)
    print("Erik: You really think people are gonna believe. I still have my doubts.")
    time.sleep(2)
    print("Narrator: Suddenly two girls came out from behind the gate.")
    time.sleep(2)
    truth = input("Stranger: Are you truly the Luminary? Y/N: ")
    if truth == "Y":
        print("Stranger: Let me see your hand " + name + ".")
        time.sleep(2)
        print("Stranger: Ut oppressa vestigia nostra fulgur revelare verum heros")
        time.sleep(2)
        print("Narrator: All of a sudden the mark of the luminary appeared on", name)
        time.sleep(2)
        print("Erik: Never had a doubt.")
        time.sleep(2)
        print("Jessie: My name is Jessica and this is my mute sister Tania")
        time.sleep(2)
        print("Jeessie: It's our duty to unlock your Luminary powers")
        time.sleep(2)
        print("Jessie: So it's time we accomplish that goal")
        time.sleep(2)
        Judgement()
    elif truth == "N":
        print("Stranger: Let me see your hand", name)
        time.sleep(2)
        print("Stranger: Ut oppressa vestigia nostra fulgur revelare verum heros")
        time.sleep(2)
        print("Narrator: All of a sudden the mark of the luminary appeared on", name)
        time.sleep(2)
        print("Erik: Did you really not know?!")
        time.sleep(2)
        print("Erik: Never had a doubt.")
        time.sleep(2)
        print("Jessie: My name is Jessica and this is my mute sister Tania")
        time.sleep(2)
        print("Jeessie: It's our duty to unlock your Luminary powers")
        time.sleep(2)
        print("Jessie: So it's time we accomplish that goal")
        Judgement()
    else:
        print("Stranger: Shut up already")
        time.sleep(2)
        print("Stranger: Let me see your hand", name)
        time.sleep(2)
        print("Stranger: Ut oppressa vestigia nostra fulgur revelare verum heros")
        time.sleep(2)
        print("Narrator: All of a sudden the mark of the luminary appeared on", name)
        time.sleep(2)
        print("Erik: Next time just answer the question stupid...")
        time.sleep(2)
        print("Erik: Never had a doubt.")
        time.sleep(2)
        print("Jessie: My name is Jessica and this is my mute sister Tania")
        time.sleep(2)
        print("Jeessie: It's our duty to unlock your Luminary powers.")
        time.sleep(2)
        print("Jessie: So it's time we accomplish that goal.")
        time.sleep(2)
        Judgement()
Intro()

